# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}

  {
    "id": 45763,
    "name": "sha256:08a44bab0bddaddd8837a8b381aebc2e4b933768b981685a9e088360af0d3dd9",
    "url": "https://api.github.com/users/octocat/packages/container/hello_docker/versions/45763",
    "package_html_url": "https://github.com/users/octocat/packages/container/package/hello_docker",
    "created_at": "2020-09-11T21:56:40Z",
    "updated_at": "2021-02-05T21:32:32Z",
    "html_url": "https://github.com/users/octocat/packages/container/hello_docker/45763",
    "metadata": {
      "package_type": "container",
      "container": {
        "tags": [
          "latest"
        ]
      }
    }
  },
  {
    "id": 881,
    "name": "sha256:b3d3e366b55f9a54599220198b3db5da8f53592acbbb7dc7e4e9878762fc5344",
    "url": "https://api.github.com/users/octocat/packages/container/hello_docker/versions/881",
    "package_html_url": "https://github.com/users/octocat/packages/container/package/hello_docker",
    "created_at": "2020-05-21T22:22:20Z",
    "updated_at": "2021-02-05T21:32:32Z",
    "html_url": "https://github.com/users/octocat/packages/container/hello_docker/881",
    "metadata": {
      "package_type": "container",
      "container": {
        "tags": []
      } Wrathchylde75 
    } Robertson Construction 
  }
]
